import 'package:flutter/material.dart';
import 'package:chrono_list/model/task_model.dart';

ValueNotifier<List<TaskModel>> taskList = ValueNotifier([
  TaskModel(
    id: '1',
    title: '20 Pushups',
    date: DateTime.now(),
    type: TaskType.count,
    isCompleted: false,
    isSkipped: false,
    repeatingCount: 20,
    currentCount: 0,
    timeToTrigger: '07:00',
    alarmEnabled: true,
    soundOrVibration: 'sound',
    repeatPattern: [1, 3, 5],
    dateRange: DateTimeRangeHive(
      start: DateTime.now(),
      end: DateTime.now().add(Duration(days: 7)),
    ),
    appToLaunch: null,
    folderPath: null,
    interviewQuestion: null,
    recordingPath: null,
    fluencyScore: null,
    clarityScore: null,
    confidenceScore: null,
    note: 'Start slow, then increase',
    autoAction: null,
    isFavorite: true,
    createdAt: DateTime.now(),
    lastModified: DateTime.now(),
  ),
  TaskModel(
    id: '2',
    title: 'Answer: Tell me about yourself',
    date: DateTime.now(),
    type: TaskType.appPerform,
    isCompleted: false,
    isSkipped: false,
    repeatingCount: null,
    currentCount: null,
    timeToTrigger: '09:00',
    alarmEnabled: true,
    soundOrVibration: 'vibration',
    repeatPattern: null,
    dateRange: null,
    appToLaunch: null,
    folderPath: null,
    interviewQuestion: 'Tell me about yourself',
    recordingPath: null,
    fluencyScore: null,
    clarityScore: null,
    confidenceScore: null,
    note: 'Keep it under 2 mins',
    autoAction: null,
    isFavorite: false,
    createdAt: DateTime.now(),
    lastModified: DateTime.now(),
  ),
  TaskModel(
    id: '3',
    title: 'Launch Telegram Group',
    date: DateTime.now(),
    type: TaskType.appLaunch,
    isCompleted: false,
    isSkipped: false,
    repeatingCount: null,
    currentCount: null,
    timeToTrigger: null,
    alarmEnabled: false,
    soundOrVibration: null,
    repeatPattern: null,
    dateRange: null,
    appToLaunch: 'org.telegram.messenger',
    folderPath: null,
    interviewQuestion: null,
    recordingPath: null,
    fluencyScore: null,
    clarityScore: null,
    confidenceScore: null,
    note: null,
    autoAction: 'alert_data_usage',
    isFavorite: false,
    createdAt: DateTime.now(),
    lastModified: DateTime.now(),
  ),
  // 4. Folder organization task
  TaskModel(
    id: '4',
    title: 'Organize Project Files',
    date: DateTime.now(),
    type: TaskType.folderOpen,
    isCompleted: false,
    isSkipped: false,
    repeatingCount: null,
    currentCount: null,
    timeToTrigger: '16:00',
    alarmEnabled: true,
    soundOrVibration: 'vibration',
    repeatPattern: [2, 4],
    dateRange: null,
    appToLaunch: null,
    folderPath: '/storage/emulated/0/Documents/Projects',
    interviewQuestion: null,
    recordingPath: null,
    fluencyScore: null,
    clarityScore: null,
    confidenceScore: null,
    note: 'Clean up junk and unused files',
    autoAction: 'open_file_manager',
    isFavorite: false,
    createdAt: DateTime.now(),
    lastModified: DateTime.now(),
  ),

  // 5. Record mock interview answer
  TaskModel(
    id: '5',
    title: 'Record Answer: Why this company?',
    date: DateTime.now(),
    type: TaskType.appPerform,
    isCompleted: false,
    isSkipped: false,
    repeatingCount: null,
    currentCount: null,
    timeToTrigger: '18:00',
    alarmEnabled: true,
    soundOrVibration: 'sound',
    repeatPattern: null,
    dateRange: null,
    appToLaunch: null,
    folderPath: null,
    interviewQuestion: 'Why do you want to work here?',
    recordingPath: '/recordings/company_answer.mp3',
    fluencyScore: 4.5,
    clarityScore: 4.0,
    confidenceScore: 4.2,
    note: 'Relate to company values and culture',
    autoAction: 'analyze_audio',
    isFavorite: true,
    createdAt: DateTime.now(),
    lastModified: DateTime.now(),
  ),

  // 6. Daily fluency practice
  TaskModel(
    id: '6',
    title: 'Fluency Drill',
    date: DateTime.now(),
    type: TaskType.count,
    isCompleted: false,
    isSkipped: false,
    repeatingCount: 5,
    currentCount: 0,
    timeToTrigger: '08:30',
    alarmEnabled: true,
    soundOrVibration: 'sound',
    repeatPattern: [1, 2, 3, 4, 5],
    dateRange: DateTimeRangeHive(
      start: DateTime.now(),
      end: DateTime.now().add(Duration(days: 30)),
    ),
    appToLaunch: null,
    folderPath: null,
    interviewQuestion: null,
    recordingPath: null,
    fluencyScore: null,
    clarityScore: null,
    confidenceScore: null,
    note: 'Practice tongue twisters',
    autoAction: null,
    isFavorite: false,
    createdAt: DateTime.now(),
    lastModified: DateTime.now(),
  ),

  // 7. Review AI scores
  TaskModel(
    id: '7',
    title: 'Review Feedback from AI',
    date: DateTime.now(),
    type: TaskType.feedback,
    isCompleted: false,
    isSkipped: false,
    repeatingCount: null,
    currentCount: null,
    timeToTrigger: '21:00',
    alarmEnabled: false,
    soundOrVibration: null,
    repeatPattern: null,
    dateRange: null,
    appToLaunch: null,
    folderPath: null,
    interviewQuestion: null,
    recordingPath: '/feedback/last_response.wav',
    fluencyScore: 3.8,
    clarityScore: 3.5,
    confidenceScore: 4.1,
    note: 'Focus on clarity improvement',
    autoAction: 'highlight_weak_spots',
    isFavorite: false,
    createdAt: DateTime.now(),
    lastModified: DateTime.now(),
  ),
  TaskModel(
  id: '8',
  title: 'Auto App Performance Test',
  date: DateTime.now(),
  type: TaskType.appLaunch,
  isCompleted: false,
  isSkipped: false,
  repeatingCount: null,
  currentCount: null,
  timeToTrigger: '23:00',
  alarmEnabled: false,
  soundOrVibration: null,
  repeatPattern: null,
  dateRange: null,
  appToLaunch: 'com.auto.clicker', // or the package name of the AutoClicker app
  folderPath: null,
  interviewQuestion: null,
  recordingPath: null,
  fluencyScore: null,
  clarityScore: null,
  confidenceScore: null,
  note: 'Ensure AutoClicker script is preloaded',
  autoAction: 'start_autotest',
  isFavorite: false,
  createdAt: DateTime.now(),
  lastModified: DateTime.now(),
),
TaskModel(
  id: '9',
  title: 'Check Notifications and Emails',
  date: DateTime.now(),
  type: TaskType.feedback,
  isCompleted: false,
  isSkipped: false,
  repeatingCount: null,
  currentCount: null,
  timeToTrigger: '10:00',
  alarmEnabled: false,
  soundOrVibration: null,
  repeatPattern: [0, 1, 2, 3, 4, 5, 6],
  dateRange: null,
  appToLaunch: null,
  folderPath: null,
  interviewQuestion: null,
  recordingPath: null,
  fluencyScore: null,
  clarityScore: null,
  confidenceScore: null,
  note: 'Avoid missing important updates',
  autoAction: null,
  isFavorite: false,
  createdAt: DateTime.now(),
  lastModified: DateTime.now(),
),
TaskModel(
  id: '10',
  title: 'Drink Water Reminder',
  date: DateTime.now(),
  type: TaskType.count,
  isCompleted: false,
  isSkipped: false,
  repeatingCount: 1,
  currentCount: 0,
  timeToTrigger: '12:30',
  alarmEnabled: true,
  soundOrVibration: 'vibration',
  repeatPattern: [0, 1, 2, 3, 4, 5, 6],
  dateRange: null,
  appToLaunch: null,
  folderPath: null,
  interviewQuestion: null,
  recordingPath: null,
  fluencyScore: null,
  clarityScore: null,
  confidenceScore: null,
  note: 'Stay hydrated!',
  autoAction: 'notify',
  isFavorite: false,
  createdAt: DateTime.now(),
  lastModified: DateTime.now(),
),
TaskModel(
  id: '11',
  title: 'Auto Backup Notes',
  date: DateTime.now(),
  type: TaskType.folderOpen,
  isCompleted: false,
  isSkipped: false,
  repeatingCount: null,
  currentCount: null,
  timeToTrigger: '22:00',
  alarmEnabled: false,
  soundOrVibration: null,
  repeatPattern: [1, 2, 3, 4, 5],
  dateRange: null,
  appToLaunch: null,
  folderPath: '/backups/notes',
  interviewQuestion: null,
  recordingPath: null,
  fluencyScore: null,
  clarityScore: null,
  confidenceScore: null,
  note: 'Runs backup script automatically',
  autoAction: 'run_backup',
  isFavorite: false,
  createdAt: DateTime.now(),
  lastModified: DateTime.now(),
),

]);
